### ISSUE TITLE
Possible to use realtime "streaming" database on dart:io?

### ISSUE THREAD

**Issue by Pacane** [FirebaseExtended/firebase-dart#107]
Hi, 

So far on the server side I've only been able to use the REST api, but I was wondering if there were a way to use the streaming database API on the server as of right now?

Thanks!

**Comment by kevmoo** [comment]
We'd have to port it to Dart. The code is available if you're interested - https://github.com/firebase/firebase-js-sdk

**Comment by arrrrny** [comment]
@kevmoo There are 3 half-baked packages by the efforts of community members. It would be really nice if dart-team launches an official dart firebase sdk that works on server not only on web.
There are SDKs for almost all other languages except dart. I really want to be able to have console app pure in dart.

**Comment by kevmoo** [comment]
Closing as not likely – at least not in this packaged.
