### ISSUE TITLE
Looking for more community contributors

### ISSUE THREAD

**Issue by kevmoo** [FirebaseExtended/firebase-dart#150]
Interested in helping to maintain and improve this package?

@Janamou and I love to help, but we're also crazy busy – and doing this entirely in free time.

Please let us know if you'd be willing to help with code reviews, improvements, and keep up-to-date with underlying platform features.

Please reply to this issue – give references to any relevant Dart projects you've worked on.

**Comment by pulyaevskiy** [comment]
I should probably leave a mention here about two packages I've been working on myself :-)

Firebase Admin SDK interop: 
https://pub.dartlang.org/packages/firebase_admin_interop/versions/1.0.0-dev.3.0

Firebase Functions interop:
https://pub.dartlang.org/packages/firebase_functions_interop/versions/1.0.0-dev.1.0

I've just released first dev versions of 1.0.0 branch which target Dart 2.

Not sure if I'll be able to contribute to this package myself though. :(

**Comment by grundid** [comment]
I'd be interested in adding app calls support:
https://firebase.google.com/docs/functions/callable

Can you point me how to start?

**Comment by kevmoo** [comment]
@grundid – it's weird that the `functions` method is not documented here - https://firebase.google.com/docs/reference/js/firebase

This will be tricky to test since you need a function on the backend, but I'd welcome you starting. See how the other top-level functions are implemented. It'll likely take some trial and error.

@jimmyff – look around https://firebase.google.com/docs/reference/js/ for things that aren't implemented yet and dive in. I'd especially recommend things that you need/want.

**Comment by emailsubjekt** [comment]
I'd like to help but don't even know what language you guys are using?
Also, you're doing this in your free time? I thought Google's Firebase was being built by a well paid team of specialized engineers not by contributions from people who don't even get paid nor are even connected to the project? What sorcery is this?

**Comment by ditman** [comment]
@hterkelsen and I can probably lend a hand here!

**Comment by samtstern** [comment]
@emailsubjekt the "FirebaseExtended" org contains projects that are not officially supported by the Firebase team but are often worked on by individual Googlers with help from the community.

There's a huge range of what "not official" means but mostly it means "Firebase Support can't help when you run into issues".  For instance projects like this one and FlutterFire are well-maintained by excellent people like @kevmoo or @kroikie and get updates all the time.  Other repos in this organization are one-time examples we published for a specific need and don't plan to update.

I hope that makes sense and if you do choose to contribute we will be excited to have you on board!

**Comment by kevmoo** [comment]
I'm back in the office in a couple of weeks and will sync with @hterkelsen on our plans here.

I don't know if I'd call this "excellently maintained" (although thanks, @samtstern ) – more like best effort and/or when I have time.
