### ISSUE TITLE
Feature request: Firebase admin sdk – native Dart VM

### ISSUE THREAD

**Issue by lasseschmitt** [FirebaseExtended/firebase-dart#152]
Hey, 

I would like to use the firebase admin sdk from my backend dart application. Is this already possible and if not is it planed?

**Comment by Janamou** [comment]
Hi @DrivEddy, I think that this is not planned for this package. This package mirrors the JS SDK only.

**Comment by kevmoo** [comment]
We could expand the `firebase_io` package to support more scenarios, but it make be tough

**Comment by pulyaevskiy** [comment]
Just an FYI, I've published first 1.0.0 development version a few days ago:
https://pub.dartlang.org/packages/firebase_admin_interop/versions/1.0.0-dev.3.0

**Comment by DrivEddy** [comment]
Thanks @pulyaevskiy The problem is, that Im running on DartVM and not on the node runtime.

**Comment by kevmoo** [comment]
Doing this will be a lot of work. Pull requests welcome!

**Comment by long1eu** [comment]
https://github.com/fluttercommunity/firebase_flutter_sdk contains just the firestore implementation. It's a port from java.

**Comment by SwissCheese5** [comment]
This is still in demand.

**Comment by kevmoo** [comment]
This work is not going to happen in this package. We're just focusing on the JS wrapper.
