### ISSUE TITLE
feature request: implement support for calling firebase functions "Functions.httpsCallable()"

### ISSUE THREAD

**Issue by tomas259** [FirebaseExtended/firebase-dart#186]

**Comment by timtraversy** [comment]
@admins, if I just port this simple Cloud Functions code from the FlutterFire library, can it be added to the firebase-dart package? It really just makes an HTTP request and returns data.
https://github.com/flutter/plugins/blob/master/packages/cloud_functions/lib/cloud_functions.dart

**Comment by kevmoo** [comment]
PR's welcome. It might be interesting to test this, though...

**Comment by formatCvt** [comment]
https://github.com/FirebaseExtended/firebase-dart/pull/219

**Comment by formatCvt** [comment]
Hi @kevmoo! How can i help with this issue/pr?

**Comment by formatCvt** [comment]
bump

**Comment by kevmoo** [comment]
This PR seems left behind - https://github.com/FirebaseExtended/firebase-dart/pull/219 – you might try to run with it?

**Comment by formatCvt** [comment]
i've tried. The `data` parameter is not optional and there is no implementation for change function location (region), i've rolled back our project to `onRequest` from `onCall`

**Comment by flowhorn** [comment]
Implementing Regions should be that though? Could this be integrated as well? Would be really helpful.

**Comment by kevmoo** [comment]
Pull requests welcome...
