### ISSUE TITLE
Apparent Race Condition When Uploading an Image

### ISSUE THREAD

**Issue by simonrubin** [FirebaseExtended/firebase-dart#191]
Using task.onStateChanged to detect when the upload is successful. Unfortunately, firebase will not always set state to 'success' when the upload completes. onStateChanged will receive a last event where state == 'running' and bytesTransferred == totalBytes. After this event there are no more events that get pushed to onStateChanged.

I tried to get around this by exiting in the case where bytesTransferred == totalBytes however, this results in a race condition when I call  await task.snapshot.ref.getDownloadURL(); as it turns out that bytesTransferred == totalBytes yet the downloadUrl does not exist yet!

Code:

```
Future<String> uploadImg(File img) async {
    final task = await fb.storage().ref(PATH + img.name).put(img);
    await _monitor(task, IMG_TASK_NAME);
    final uri = await task.snapshot.ref.getDownloadURL();
    return uri.toString();
  }

 Future<void> _monitor(fb.UploadTask task, String taskName) {
    final completer =  Completer<bool>();
    task.onStateChanged.listen((fb.UploadTaskSnapshot snapshot) async {
      final state = snapshot.task.jsObject.snapshot.state;

      // fb doesn't always set state == 'success' when done :(
      final isComplete = snapshot.bytesTransferred == snapshot.totalBytes;

      if(state == 'success') {
        completer.complete();
      }
      else if(state == 'error') {
        completer.completeError(taskName);
      }
    });
    return completer.future;
  }
```
Details:
Dart VM version: 2.0.0-dev.67.0 (Tue Jul 3 18:17:07 2018 +0200) on "macos_x64"

  firebase:
    dependency: "direct main"
    description:
      name: firebase
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.1"

**Comment by kevmoo** [comment]
Closing as stale. Reopen if you still have this issue!
