### ISSUE TITLE
Timestamp microseconds support

### ISSUE THREAD

**Issue by alextekartik** [FirebaseExtended/firebase-dart#204]
Currently even though timestamps are supported on the js side (which seems to support nanoseconds - or at least microseconds in my testing), on the dart side the value is truncated to milliseconds as it is converted to DateTime (which has microsecond precision on the VM and millisecond precision in JS).

Will this change or would you consider adding the equivalent `timestampsInSnapshots` to enable a smooth migration (even though timestampsInSnapshots is set on the js side, that is actually not the case on the dart side since timestamps are converted to date in dartify).

I understand that pratically we cannot really format a date with microseconds precision on the browser but simply reading/writing a date can change it if it has microseconds precision initially.

**Comment by kevmoo** [comment]
I'd accept a pull request here!

**Comment by alextekartik** [comment]
Pull request proposed here: https://github.com/FirebaseExtended/firebase-dart/pull/205

**Comment by kevmoo** [comment]
Closing as outdated...
