### ISSUE TITLE
feature request: implement User.getIdTokenResult()

### ISSUE THREAD

**Issue by afpatmin** [FirebaseExtended/firebase-dart#209]
From [https://firebase.google.com/docs/auth/admin/custom-claims](url):
```
firebase.auth().currentUser.getIdTokenResult()
  .then((idTokenResult) => {
     // Confirm the user is an Admin.
     if (!!idTokenResult.claims.admin) {
       // Show admin UI.
       showAdminUI();
     } else {
       // Show regular user UI.
       showRegularUI();
     }
  })
  .catch((error) => {
    console.log(error);
  });
```
Custom claims is a convenient method for defining multiple user roles within an app. `User.getIdTokenResult()` allows the client to access the user's assigned roles.

**Comment by kevmoo** [comment]
See https://firebase.google.com/docs/reference/js/firebase.User.html#getidtokenresult

**Comment by siavee** [comment]
Meanwhile you can use the solution described here https://github.com/flutter/flutter/issues/20238#issuecomment-445553891
