### ISSUE TITLE
Request: Update http version

### ISSUE THREAD

**Issue by Maliffic** [FirebaseExtended/firebase-dart#211]
I am using the algolia package and it required a dependancy version of http 12 and firebase is currently using 11, can the package be updated?

**Comment by exo-pla-net** [comment]
Indeed, the functionality has been improved in http 12 for browser http requests. Firebase-dart needs updating.

**Comment by kevmoo** [comment]
This was already done at 5e24d45 – just need to publish!

**Comment by kevmoo** [comment]
Running with https://github.com/FirebaseExtended/firebase-dart/pull/213 now!

**Comment by kevmoo** [comment]
Deployed as https://pub.dartlang.org/packages/firebase/versions/5.0.3
