### ISSUE TITLE
Add support for signInWithEmailLink method

### ISSUE THREAD

**Issue by jans-y** [FirebaseExtended/firebase-dart#216]
Hello,

I would like to ask you to add support for signInWithEmailLink method in this library.

This is my implementation, I am just a beginner in Dart, that's why I didn't create PR.

**auth_interop.dart**
`external PromiseJsImpl<UserCredentialJsImpl> signInWithEmailLink(
      String email, String emailLink);`

**auth.dart**
`Future<UserCredential> signInWithEmailLink(
          String email, String emailLink) =>
      handleThenable(jsObject.signInWithEmailLink(email, emailLink))
          .then((u) => UserCredential.fromJsObject(u));`

Thank you

**Comment by kevmoo** [comment]
Fixed in https://github.com/FirebaseExtended/firebase-dart/commit/d864d1c89515df979d640d42a571de32447f4e47

Will be available in v7
