### ISSUE TITLE
Add support for Firestore Collection Group queries

### ISSUE THREAD

**Issue by jans-y** [FirebaseExtended/firebase-dart#223]
Hello,

Could you please add support for Firestore Collection Group queries?

Reference:
https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/CHANGELOG.md

Thank you.

**Comment by kevmoo** [comment]
This package is lightly maintained. Pull requests welcome.

*From: *jans-y <notifications@github.com>
*Date: *Wed, May 15, 2019 at 2:54 AM
*To: *FirebaseExtended/firebase-dart
*Cc: *Subscribed

Hello,
