### ISSUE TITLE
isSupported is not supported

### ISSUE THREAD

**Issue by martinory** [FirebaseExtended/firebase-dart#229]
Hi!
firebase.messaging.isSupported() is not supported.
Messaging does not work on iOS because the Push API is not supported and thus breaks the app on iOS when messaging is instantiated. If isSupported was supported it would be much helpful.

**Comment by martinory** [comment]
I added the support to a fork this fork: https://github.com/martinory/firebase-dart/commit/905bc1e405a010a73e6f981f6573c3c4dae49f8e

**Comment by kevmoo** [comment]
PR welcome!

Please add a test, etc.
