### ISSUE TITLE
Make it work with build_web_compilers >= 2.0.0

### ISSUE THREAD

**Issue by mkiisoft** [FirebaseExtended/firebase-dart#242]
I'm using the plugin with:

`build_web_compilers: '>=1.0.0 <2.0.0'`

but this is giving me all kinds of limitations with other Flutter Web libraries as everyone is using >= 2.0.0

Is there any news about this? will it come with the next update?

**Comment by kevmoo** [comment]
This is already fixed. Just needs to be published!
