### ISSUE TITLE
Firestore runTransaction() fails

### ISSUE THREAD

**Issue by netcyrax** [FirebaseExtended/firebase-dart#245]
I am trying to do a read-write in the same transaction in Firestore, but fails with the following message:
```
dart_sdk.js:102091 EXCEPTION: TypeError: dart.global.firebase.Promise is not a constructor
STACKTRACE: 
dart:sdk_internal                                                                             <fn>
package:angular/src/core/change_detection/packages/angular/src/core/zone/ng_zone.dart 117:11  <fn>
package:stack_trace                                                                           <fn>
package:angular/src/core/change_detection/packages/angular/src/core/zone/ng_zone.dart 132:18  <fn>
dart:sdk_internal                                                                             run
package:angular/src/core/change_detection/packages/angular/src/core/zone/ng_zone.dart 129:18  [_run]

dart:sdk_internal                                                                             scheduleMicrotask
package:angular/src/core/change_detection/packages/angular/src/core/zone/ng_zone.dart 125:11  [_scheduleMicrotask]
```

Code:
```
    db = firestore();
    ref = db.collection("collection");

    await db.runTransaction(
        (transaction) async {
          final snapshot = await transaction.get(ref.doc(id));
          final data = snapshot.data();
          data['count'] = data['count']+1;
          await transaction.update(ref.doc(id), data: data);
        }
    );
```

**Comment by kevmoo** [comment]
Which version of the package are you using?

**Comment by netcyrax** [comment]
firebase: ^5.0.4
angular: ^5.3.0

Thanks!

**Comment by el-mimoso** [comment]
We are facing a similar exception while running on iOS, in andriod works fine.
LOG:
Exception has occurred. PlatformException (PlatformException(9, Transaction failed all retries.: Every document read in a transaction must also be written in that transaction., null))
Using cloud_firestore: ^0.12.9+2

FLUTTER DOCTOR
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale es-MX)
• Flutter version 1.9.1+hotfix.4 at /Users/danielcastropineda/flutter
• Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
• Engine revision b863200c37
• Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
• Android SDK at /Users/danielcastropineda/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.0
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.1, Build version 11A1027
• CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 36.0.1
• Dart plugin version 183.6270
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.5.1

[✓] Connected device (1 available)
• iPhone •... • ios • iOS 12.4.2

DocumentReference docRef = Firestore.instance
.collection('e')
.document(escuelas.elementAt(indiceTemporal))
.collection('o')
.document(_userID);

Firestore.instance.runTransaction((Transaction transaction) async { // Exception is thrown
DocumentSnapshot docSnapshot = await transaction.get(docRef);
if (docSnapshot.exists){
await transaction.update(docRef,{'x': DateTime.now()});//prueba para ios
documentosPreorden.add(docSnapshot);
}

**Comment by kevmoo** [comment]
You may need to add a polyfil for `Promise` on iOS. 

Maybe https://www.npmjs.com/package/promise-polyfill ?

**Comment by kevmoo** [comment]
Closing out. Please comment if there are other issues.

**Comment by IsaacEduardo** [comment]
I'm going through the same situation. I intend to finalize the order in my app, but every time I send this function I unfortunately get this null transaction error. If anyone has a solution I would appreciate it very much.
`//pegando os id dos pedidos
  Future<int> _getOrderId() async {
    //especificar as refererncia, pegando as transações
    final ref = firestore.document('aux/ordercounter');
    try {
      final result = await firestore.runTransaction((tx) async {
        final doc = await tx.get(ref);
        final orderId = doc.data['current'] as int;
        await tx.update(ref, {'current': orderId + 1});
        return {'orderId': orderId};
      }, timeout: const Duration(seconds: 10));
      return result['orderId'] as int;
    } catch (e) {
      debugPrint(e.toString());
      return Future.error('Falha ao gerar o número do pedido');
    }
  }

`
Erros
E/CloudFirestorePlugin(26439): java.lang.Exception: DoTransaction failed: NoSuchMethodError: The method '[]' was called on null.
E/CloudFirestorePlugin(26439): Receiver: null
E/CloudFirestorePlugin(26439): Tried calling: []("current")
E/CloudFirestorePlugin(26439): java.util.concurrent.ExecutionException: java.lang.Exception: DoTransaction failed: NoSuchMethodError: The method '[]' was called on null.
E/CloudFirestorePlugin(26439): Receiver: null
E/CloudFirestorePlugin(26439): Tried calling: []("current")
