### ISSUE TITLE
Is Auth complete? 

### ISSUE THREAD

**Issue by hpoit** [FirebaseExtended/firebase-dart#246]
Hi there. Is Auth supposed to look like this? 
![image](https://user-images.githubusercontent.com/3711100/64476131-9696aa00-d161-11e9-81c2-a4b3e7cff870.png)

**Comment by kevmoo** [comment]
Look in the chrome dev tools. Is there any console output?

**Comment by hpoit** [comment]
Hi Kevin, in the console I get 
![image](https://user-images.githubusercontent.com/3711100/64534989-e2298f00-d2ec-11e9-9d9b-9c9b1029bcbb.png)

**Comment by kevmoo** [comment]
There you go. Look in the lib/src/assets directory about configuring
`config.json`
