### ISSUE TITLE
Has anyone tried to integrate firebase-dart with the geofire library for geo queries?

### ISSUE THREAD

**Issue by barapa** [FirebaseExtended/firebase-dart#250]
I am interested in integrating with https://github.com/firebase/geofire-js/blob/master/docs/reference.md.

**Comment by hterkelsen** [comment]
Not that I know of. If you decide to take on the project, it should probably be in a separate repo, since the goal of `firebase-dart` is to give a Dart client for the core Firebase SDK. I'm sure if you write a `geofire-dart` repo there will be other users!
