### ISSUE TITLE
[Question] Anyone working on a OAuthProvider?

### ISSUE THREAD

**Issue by AlexandreRoba** [FirebaseExtended/firebase-dart#252]
Currently we are limitedd to Google, Facebook, twitter, Github and Phone. I need to integrate with Microsoft. Usually I use the OAuthPRovider.... Is this possible?

**Comment by AlexandreRoba** [comment]
I forked the project and started working on it. The change seems to be straight forward.

Any reason that i should not do it?

**Comment by kevmoo** [comment]
Fixed in https://github.com/FirebaseExtended/firebase-dart/pull/253 – thanks!
