### ISSUE TITLE
Version 6.0.0 does not exists in Pub

### ISSUE THREAD

**Issue by sh0umik** [FirebaseExtended/firebase-dart#254]
The master branch says import 6.0.0 but this version does not exists in pub.dev.

```
dependencies:
  firebase: ^6.0.0
```

**Comment by kevmoo** [comment]
It has not been published yet. Is this a formal request?

**Comment by kevmoo** [comment]
Fixed in bb6d6dd789d120f86a5d2dd070063fe4569d1162
