### ISSUE TITLE
updateProfile not working

### ISSUE THREAD

**Issue by youmnay** [FirebaseExtended/firebase-dart#258]
Hi! I am new to flutter and I have a problem please.
I created a user through the console and tried to update the user info through code in flutter web application.
I created userprofile instance:
UserProfile fbP = UserProfile();
   fbP.displayName = "Youmna";
   fbP.photoURL = "";

and passed it to updateProfile function:
authFB.currentUser.updateProfile(fbP);

--authFB is my Firebase.Auth attribute

and then I tried to print the display name, but it gave me null!
print(authFB.currentUser.displayName);

However I tried to print the email and it printed it correctly.
print(authFB.currentUser.email);

Would you please help with this?

**Comment by kevmoo** [comment]
`updateProfile` is async – you need to wait for it to complete before you check to see if the value has been saved!
