### ISSUE TITLE
This operation is restricted to administrators only

### ISSUE THREAD

**Issue by michealchow** [FirebaseExtended/firebase-dart#259]
I got this message when i was trying to sign in anonymously from the web.

> FirebaseError: This operation is restricted to administrators only.
> (auth/admin-restricted-operation)

Step to reproduce:
```
1. fb.Auth auth = fb.auth();
2. await auth.signInAnonymously();
```

**Comment by AlexMeuer** [comment]
I'm having the same issue.

**Comment by ghulamMustafaRaza** [comment]
Enable signInAnonymously from sign-in methods

**Comment by dikaro** [comment]
@ghulamMustafaRaza Thankyou buddy :)

**Comment by thakurvijendar** [comment]
I am getting the same error even after enabeling signInAnonymously from sign-in methods

**Comment by Chetan-Goyal** [comment]
I have enabled Anonymous in Sign-in Options but it's still showing the same error message.

**Comment by ghulamMustafaRaza** [comment]
@dikaro You're welcome

**Comment by RiyaadHossain** [comment]
I am also getting the same error. I tried for approximately an hour. Even I talked to my Bootcamp support instructor. He also failed to solve it. It's totally disappointing😒
![Screenshot 2022-04-11 180707](https://user-images.githubusercontent.com/96947874/162736071-aab5cbec-2987-4968-8442-1f970f7a0372.png)
