### ISSUE TITLE
Error while using storage 

### ISSUE THREAD

**Issue by saisantosh2095** [FirebaseExtended/firebase-dart#263]
-----------------------------------Error log----------------

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NativeJavaScriptObject object was thrown building Builder:
[object Object]

User-created ancestor of the error-causing widget was:
MaterialApp org-dartlang-app:///packages/dashboard/main.dart:39:14

When the exception was thrown, this was the stack:
Non-error `[object Object]` thrown by JS does not have stack trace.
Caught in Dart at:

package:build_web_compilers/src/dev_compiler/dart_sdk.js 6066:23    missing
package:build_web_compilers/src/dev_compiler/dart_sdk.js 3982:14    stackTrace
package:flutter/src/widgets/framework.dart 3980:17                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 5165:14                  mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 5165:14                  mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 4111:11                  [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 5165:14                  mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 5165:14                  mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 4111:11                  [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 4111:11                  [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 5165:14                  mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 5165:14                  mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 4111:11                  [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 5165:14                  mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 4111:11                  [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 3941:5                   [_firstBuild]
package:flutter/src/widgets/framework.dart 4111:11                  [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                   mount
package:flutter/src/widgets/framework.dart 3109:13                  inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                  updateChild
package:flutter/src/widgets/framework.dart 4939:32                  updateChildren
package:flutter/src/widgets/framework.dart 5281:17                  update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/overlay.dart 607:16                     update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 4143:5                   update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 4277:5                   update
package:flutter/src/widgets/inherited_notifier.dart 94:11           update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/framework.dart 5172:14                  update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 4143:5                   update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/framework.dart 5172:14                  update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/framework.dart 5172:14                  update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 4033:5                   update
package:flutter/src/widgets/framework.dart 2892:14                  updateChild
package:flutter/src/widgets/framework.dart 3978:16                  performRebuild
package:flutter/src/widgets/framework.dart 3755:5                   rebuild
package:flutter/src/widgets/framework.dart 2347:31                  buildScope
package:flutter/src/widgets/binding.dart 776:49                     drawFrame
package:flutter/src/rendering/binding.dart 283:5                    [_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1043:15                  [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 982:9                    handleDrawFrame
package:flutter/src/scheduler/binding.dart 898:5                    [_handleDrawFrame]
package:build_web_compilers/src/dev_compiler/dart_sdk.js 159683:23  <fn>

-----------------------------Flutter Doctor -----------------------------

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.10.14, on Mac OS X 10.15.1 19B88, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

--------------------------Index.html-----------------------------
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>dashboard</title>
</head>
<body>
<script src="https://www.gstatic.com/firebasejs/6.6.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.6.1/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.6.1/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.6.1/firebase-firestore.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.6.1/firebase-storage.js"></script>
<script src="main.dart.js" type="application/javascript"></script>
</body>
</html>

**Comment by kevmoo** [comment]
That stack trace does not have enough information to debug the problem.

Not sure what to do. 🤷‍♂

**Comment by kevmoo** [comment]
Closing out for lack of info...

**Comment by meynety** [comment]
In case someone encounters this issue, in my case it was kinda dumb, I just added the firebase-storage.js link in my index while the build watcher was running : 
-> Rebuilding the app fixed it.

**Comment by buttholeorbellybutton** [comment]
Same issue.

**Comment by raphael-bmec-co** [comment]
Okay I have some good news. 

What we are seeing: This seems to be an issue with the native error handler parsing the thrown object into an error. This appears to be because the object is of type NativeJavaScriptObject.

Good news: You can still expand the NativeJavaScriptObject to see the actual error being thrown by the Firebase API by referencing error.code, error.message etc etc.

Happy coding.

**Comment by bankenro** [comment]
![image](https://user-images.githubusercontent.com/30939186/89330324-b0808b80-d655-11ea-9c81-0f977aee44b8.png)
Expected a value of type 'JSObject<Tc>', but got one of type 'NativeJavaScriptObject'
