### ISSUE TITLE
Auth currentUser isn't persisted

### ISSUE THREAD

**Issue by jonjon1123** [FirebaseExtended/firebase-dart#265]
It seems the `setPersistence` property isn't being honored. I have code similar to below. After I log in then refresh the page, `currentUser` is null therefore forcing me to login again. It seems like the state of the authentication that was performed previously is completely gone. This also occurs when an app reload is done via VS Code making rapid development very difficult.

```dart
App app = initializeApp(
   ...
);
app.auth().setPersistence(Persistence.LOCAL)

.
.
.

// user is null here after page refresh
User user = app.auth().currentUser;
```

How do I implement a "remember me" type functionality using this lib?

**Comment by kevmoo** [comment]
It should be one-to-one w/ the JS API, as long as all of the corresponding APIs are exposed.

Did you await `setPersistence`? Were there any errors?

**Comment by kevmoo** [comment]
I don't see anything in particular here: https://firebase.google.com/docs/reference/js/firebase.auth.Auth.html#set-persistence

**Comment by jonjon1123** [comment]
I added in the `await` but it still behaves the same. It is like the underlying persistence of the current user information is not kept through a browser refresh or reload in VS Code. I am using Flutter Web for this. Could it be related to something in Flutter Web?

**Comment by kevmoo** [comment]
Does the auth demo work for you?

https://github.com/FirebaseExtended/firebase-dart/tree/master/example/auth

**Comment by cfregin** [comment]
app.auth().currentUser is not async like in [firebase_auth](https://pub.dev/packages/firebase_auth).
You should wait until the fb auth is initialized. I hacked it now with 
```
@override
  Future<bool> isSignedIn() async {
    await Future.delayed(Duration(seconds: 1));
    User currentUser = _firebaseAuth.currentUser;
    return currentUser != null;
  }
```

**Comment by kevmoo** [comment]
I doubt this has anything to do w/ Flutter web. I'm at a bit of a loss 🤷‍♂

**Comment by jonjon1123** [comment]
FWIW, the hack @cfregin mentioned also worked for me.

**Comment by CEbbinghaus** [comment]
The Delay can be Halved. Using
`await Future.delayed(Duration(milliseconds: 500));`
gives me reliable Data and is a lot closer to Instant

**Comment by woutervanwijk** [comment]
For me, the hack also worked. I'm curious why it's not async

**Comment by kleinpetr** [comment]
I have the same problem.. why the currentUser is not async?

**Comment by kleinpetr** [comment]
@CEbbinghaus when I set 500ms it working only when I reload the page but when I close the tab and open new tab, then is null. I must use minimal 1000ms.. 

But I don't want dependent to some time delay, it is too dangerous to use in production. I hope for update of library will be very soon. Thank you

**Comment by kleinpetr** [comment]
This is little trick to use it as Future as well :-)

```
Future<firebase.User> getCurrentUser() {
    final completer = Completer<firebase.User>();
    firebase.auth().onAuthStateChanged.listen((firebase.User user) {
      completer.complete(user);
    });

    return completer.future;
  }
```
and then you can use

`_firebaseUser = await getCurrentUser();`

**Comment by barriehadfield** [comment]
I had the same problem and it took a while to find the solution:

app.auth().currentUser will always be null when the page first loads. You can only rely on this value being set after onAuthStateChanged has returned a valid user (this takes about half a second). 

```
firebase.auth().onAuthStateChanged((user) {
      if (user == null)
        // set a local state as we do not have the current user yet
      else
        // only now will  app.auth().currentUser give you a valid user
 });
```

Your UI code needs to handle this state change.

**Comment by aaahrens** [comment]
Why is this marked as more information needed? I have several apps that have to hack around this in production.

Even auth state streams are not accurate because when auth loads it fires another event.

**Comment by kevmoo** [comment]
I could add `FutureOr<User> get waitCurrentUser` to `Auth`.

Would that work for folks?

**Comment by iwasscience** [comment]
> I could add `FutureOr<User> get waitCurrentUser` to `Auth`.
> 
> Would that work for folks?

that would be very helpful!
