### ISSUE TITLE
[web]: Unable to find firebase module

### ISSUE THREAD

**Issue by Ahmadre** [FirebaseExtended/firebase-dart#283]
When I import: ```'package:firebase/firebase.dart'```, I can't run Flutter Web (Version: 1.12.17-pre.47). I get following error:

```
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:firebase/firebase.dart' as fb;` from luitsapp|lib/main.dart at 7:1
`import 'package:firebase/firebase.dart' as fb;` from luitsapp|lib/Screens/CredentialScreens/login.dart at 9:1

Failed after 1.0sFailed to build application for the Web.
```

Please help! I also tried version 6.0.0 and 5.0.0 😢 

And yes of course I ran multiple times: flutter packages get.

Note: I tried EVERYTHING: changed the Dart SDK...changing Flutter from master 1.12.* to 1.10.14 (which is suggested here somewhere)...Nothing works!

Now i recognized, that promiseToFuture and a lot of other html stuff breaks also my flutter VM to work...

_Gesendet von meinem Pixel 2 XL mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Balloonist** [comment]
Having exactly the same issue ...

**Comment by Ahmadre** [comment]
After updating to firebase 7.1.0 my issue was solved. Thanks Firebase-Dart team ❤️
