### ISSUE TITLE
Uncaught TypeError: Cannot read property

### ISSUE THREAD

**Issue by praharshbhatt** [FirebaseExtended/firebase-dart#284]
Firebase auth, and cloudfirestore work flawlessly when run in debug.

Although when hosted in firebase hosting, although the webpage displays correctly, the Authentication function throws the following error:

```
js_helper.dart:1342 Uncaught TypeError: Cannot read property 'hJ' of null
    at Object.Q1 (navigator.dart:1492)
    at Object.a0f (main.dart:71)
    at vI.$1 (auth.dart:39)
    at LY.LB (zone.dart:1381)
    at LY.qa (zone.dart:1380)
    at Ka.$0 (future_impl.dart:107)
    at Object.iz (future_impl.dart:711)
    at O.k0 (future_impl.dart:526)
    at IK.ck (async_patch.dart:204)
    at Object.a3 (async_patch.dart:260)
```
Authentication Class source code:
https://gist.github.com/praharshbhatt/b334de9d7395908c11cafce1f4ffc6c1

Please have a look at the full project here: https://github.com/praharshbhatt/flutter_web_mobile_firebase

**Comment by kevmoo** [comment]
Wonder if this is related to https://github.com/FirebaseExtended/firebase-dart/pull/282

**Comment by praharshbhatt** [comment]
I don't think so. This happens in both Google signin, and email authentication.
I'm already using the version 7.5.2

**Comment by praharshbhatt** [comment]
Any solution to this?

**Comment by hterkelsen** [comment]
@praharshbhatt we are adding web support to `package:firebase_auth` and `package:cloud_firestore` very soon (see https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web)

Please try these packages out in your Flutter web app

**Comment by kevmoo** [comment]
Are you still having this issue?
