### ISSUE TITLE
Not Support Query operators array-contains-any and in

### ISSUE THREAD

**Issue by dennougorilla** [FirebaseExtended/firebase-dart#289]
> Query operators
The where() method takes three parameters: a field to filter on, a comparison operation, and a value. The comparison can be <, <=, ==, >, >=, array-contains, in, or array-contains-any. For iOS, Android, and Java, the comparison operator is explicitly named in the method.
https://cloud.google.com/firestore/docs/query-data/queries#query_operators

**Comment by dennougorilla** [comment]
https://github.com/FirebaseExtended/firebase-dart/blob/ec106a9e65656c8c8c88d12fad6d88e3ba7f7c8b/lib/src/interop/firestore_interop.dart#L230-L231

https://github.com/FirebaseExtended/firebase-dart/blob/ec106a9e65656c8c8c88d12fad6d88e3ba7f7c8b/lib/src/firestore.dart#L536-L538

**Comment by kevmoo** [comment]
The docs may outdated, but these operator should still work...

**Comment by kevmoo** [comment]
Reponing to flag updating docs!

**Comment by kevmoo** [comment]
Fixed in 32539e94cdba5a56c878a06190b542d32169d148
