### ISSUE TITLE
Collection group query not working with where clause

### ISSUE THREAD

**Issue by CoderJerry** [FirebaseExtended/firebase-dart#290]
fb
        .firestore()
        .collectionGroup(CONSULTATIONS_PATH)
        .onSnapshot
        .map((qs) =>
            qs.docs.map((d) => ConsultationModel.fromJson(d.data())).toList());

above code is working as expected but when I am adding any where clause like below than its failing no matter whatever clause I add

fb
        .firestore()
        .collectionGroup(CONSULTATIONS_PATH)
        .where("dateTime", ">=", 1576525560000)
        .onSnapshot
        .map((qs) =>
            qs.docs.map((d) => ConsultationModel.fromJson(d.data())).toList());

**Comment by kevmoo** [comment]
Are you importing the latest JS library in your application?

**Comment by CoderJerry** [comment]
`environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  geo_firestore: ^0.0.1
  get_it: ^3.0.3
  recase: ^2.0.1
  rxdart: ^0.22.4
  datetime_picker_formfield: ^0.4.3
  device_preview: ^0.2.6
  data_connection_checker: ^0.3.4
  cloud_functions: ^0.4.1+4
  razorpay_flutter: ^1.1.2
  flutter_screenutil: ^0.6.1
  agora_rtc_engine: ^1.0.1
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.22.1
  equatable: ^0.6.1
  dartz: ^0.8.7
  connectivity: ^0.4.5+1
  intl: ^0.15.7


dev_dependencies:
  flutter_launcher_icons:

  flutter_test:
    sdk: flutter

  mockito: ^4.1.1`

this is my pubspec.yml dependency

and this is my index.html 
`<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>resolve_dashboard</title>
  <script src="https://cdn.agora.io/sdk/release/AgoraRTCSDK-3.0.0.js"></script>
  <script defer src="main.dart.js" type="application/javascript"></script>
</head>

<body>
  

  
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-analytics.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-firestore.js"></script>
  

  
  
  
  
  

</body>

</html>`

**Comment by kevmoo** [comment]
Do you have an index defined for CONSULTATIONS_PATH - dateTime ?

**Comment by kevmoo** [comment]
Or do you have any details on the error reported?

**Comment by CoderJerry** [comment]
No I have not created any manually. I was expecting it to throw a firebase url to create index. however I did not got any thing in console. 
This is my flutter doctor report 

[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] VS Code, 64-bit edition (version 1.40.2)
[√] Connected device (3 available)

**Comment by CoderJerry** [comment]
![image](https://user-images.githubusercontent.com/10288399/70953780-85c6d000-2090-11ea-8579-90920db3cbad.png)

After adding Exemption its working now.
Thanks a lot for the support.

**Comment by crystalneth** [comment]
The documentation consistently that an error will be shown and a URL to create the needed index will be provided. Instead the query just returns no results.

Can I suggest updating the documentation?

**Comment by mono0926** [comment]
@crystalneth #2305 might fix the problem.
