### ISSUE TITLE
Health and maintenance issues result in low score on pub.dev

### ISSUE THREAD

**Issue by aryzhov** [FirebaseExtended/firebase-dart#294]
The score of package [firebase 7.1.0](https://pub.dev/packages/firebase#-analysis-tab-) on `pub.dev` is currently 76. Specifically:
* Popularity: 96
* Health: 45
* Maintenance: 69

A low score discourages developers from using a package suggesting low quality or the lack of maintenance.

**Comment by ditman** [comment]
Looking at some of the action items in pub.dev, this looks like a quite "Good First Issue" for people to contribute stuff here, don't you think?

**Comment by kevmoo** [comment]
There is some code layout bits that could be done. I just need time – or help – to do it!

**Comment by kevmoo** [comment]
There are a lot of fixes pending, but I want to roll up the latest config bits first.

**Comment by ditman** [comment]
@kevmoo I can give you a hand, but I'm not sure what's in flight (just merging the 2 pending PRs?). If you send me an email pointing me to where I can start with, I can take a look.

**Comment by kevmoo** [comment]
@thanks, @ditman – wait till I'm back in the office. The last bit related to some dependencies that will be gnarly to dig through.

We'll make things a lot better with the PRs that are pending for the next release

**Comment by kevmoo** [comment]
* Popularity: 96
* Health: 45 –> 56
* Maintenance: 69 -> 89

Just released 7.2.0 – scores are better!

Need to update the description and turn this into a [mono_repo](https://pub.dev/packages/mono_repo) to fix the other issues

**Comment by kevmoo** [comment]
Should be fixed with https://github.com/FirebaseExtended/firebase-dart/commit/7ef81823e9f0ab0995255d389e0af017e4771bd1
