### ISSUE TITLE
Error getting `config.json`. Make sure it exists.

### ISSUE THREAD

**Issue by ompraka158** [FirebaseExtended/firebase-dart#297]
I just downloaded the zip and run the following statements:

> pub get
> pub run build_runner serve example

![Screenshot from 2020-01-21 15-08-15](https://user-images.githubusercontent.com/46670915/72793148-1bd9b180-3c60-11ea-8d69-799347213a05.png)

**Comment by kevmoo** [comment]
Yup. See https://github.com/FirebaseExtended/firebase-dart/tree/master/lib/src/assets
