### ISSUE TITLE
Error in sign in with google: Expected a value of type 'AuthProvider<JSObject<firebase.auth.AuthProvider>>', but got one of type 'GoogleAuthProvider'

### ISSUE THREAD

**Issue by ompraka158** [FirebaseExtended/firebase-dart#298]
![Screenshot from 2020-01-22 15-19-17](https://user-images.githubusercontent.com/46670915/72888968-ae4b8500-3d34-11ea-9caf-8b2c36de5b03.png)
 Below is the code I have implemented:

import 'package:angular/angular.dart';
import 'package:firebase/firebase.dart';
import '../../constants/images/fnp_images.dart';
import 'package:firebase/firebase.dart' as fb;
// import 'package:google_sign_in/google_sign_in.dart';

@Component(
  selector: 'app-login',
  templateUrl: 'login_component.html',
  styleUrls: ['login_component.css'],
)
class LoginComponent {
  // LoginCs

  LoginComponent() {
    initializeApp(
      apiKey: "XXXXXX",
      authDomain: "XXXXX");
    // auth = fb.auth();
  }
  var auth;
  var provider; 
  var name = 'Angular';
  var background_layout_img = FnpImages.s_logo;
  // Console.log(background_layout_img);
  
  void facebookLogin () async {
    provider = fb.FacebookAuthProvider();
    print(provider);
    try {
      await fb.auth().signInWithPopup(provider);
    } catch (e) {
      print("Error in sign in with facebook: $e");
    }
  }

  void googleLogin() async {
    provider = fb.GoogleAuthProvider();
    print(provider);
    try {
      await fb.auth().signInWithPopup(provider).then((res) => {
        print("Done")
      });
    } catch (e) {
      print("Error in sign in with google: $e");
    }
  }
}

Apart from this I have also added the src script for firebase in index.html

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script>
        
        (function() {
            var m = document.location.pathname.match(/^(\/[-\w]+)+\/web($|\/)/);
            document.write('<base href="' + (m ? m[0] : '/') + '" />');
        }());
    </script>

    <title>FNP Gardens</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="styles.css">
    <link rel="icon" type="image/png" href="favicon.png">

    <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-auth.js"></script>
    <script defer src="main.dart.js"></script>

**Comment by ompraka158** [comment]
Also it would be very helpful if you can add examples for social login i.e., google or git login which isn't there in the example.

**Comment by ompraka158** [comment]
I guess nobody has a solution for my problem. If so please close this.

**Comment by kevmoo** [comment]
@ompraka158 – be VERY careful pasting in code that has auth keys, etc!

**Comment by kevmoo** [comment]
Try again with the latest version – 7.2.1 – let me know if it helps!
