### ISSUE TITLE
Cloud function crashes when return type is not a Map

### ISSUE THREAD

**Issue by talent-apps** [FirebaseExtended/firebase-dart#313]
We have a cloud function  that returns an array of javascript objects.
Invoking this function causes a crash since the `data` getter of `HttpsCallableResult` returns `Map<String, dynamic>` instead of `dynamic`:

```
class HttpsCallableResult
    extends JsObjectWrapper<functions_interop.HttpsCallableResultJsImpl> {
  static final _expando = Expando<HttpsCallableResult>();

  /// Creates a new HttpsCallableResult from a [jsObject].
  static HttpsCallableResult getInstance(
      functions_interop.HttpsCallableResultJsImpl jsObject) {
    if (jsObject == null) {
      return null;
    }
    return _expando[jsObject] ??= HttpsCallableResult._fromJsObject(jsObject);
  }

  HttpsCallableResult._fromJsObject(
      functions_interop.HttpsCallableResultJsImpl jsObject)
      : super.fromJsObject(jsObject);

  Map<String, dynamic> get data => dartify(jsObject.data); <<<< WRONG RETURN VALUE
}
``` 

The function `dartify` returns a `dynamic` type, not a `Map<String, dynamic>` type.

**Comment by dustin-graham** [comment]
I have this same problem. I have a function which returns a String. The function runs normally and works on the mobile platforms, but the web SDK expects a Map and can't handled a non-map response.

**Comment by dustin-graham** [comment]
@talent-apps For me, this behavior was fixed on https://pub.dev/packages/cloud_functions/versions/0.7.0-dev.2.
