### ISSUE TITLE
Inconsistent interfaces between firebase and firebase_io

### ISSUE THREAD

**Issue by Wylarel** [FirebaseExtended/firebase-dart#333]
Hello!

I need to import `firebase` on web and `firebase_io` on mobile. Here's how I do it:
```
import 'package:firebase/firebase.dart'
  if (dart.library.io) 'package:firebase/firebase_io.dart'
  if (dart.library.html) 'package:firebase/firebase.dart';
```
It works just fine on web, but on mobile, when using firebase_io, storage() is not defined. Any idea why? How can I avoid this? (Before, I was using firebase_storage/firebase_storage.dart but that doesn't seems compatible with firebase/firebase.dart either)

**Comment by kevmoo** [comment]
Use https://pub.dev/packages/firebase_storage !
