### ISSUE TITLE
firestore listener not working as expected

### ISSUE THREAD

**Issue by suvarna84** [FirebaseExtended/firebase-dart#336]
My web application requires me to use firestore listener for a  document 'jkl. Instead of printing the updated value once,  it is repeatedly printing the value even though there is no update in the document 'jkl. 

     void switchListener() async {
          _listener = Firestore.instance
           .collection('abc')
          .document('def')
          .collection('ghi')
         .document('jkl')
         .snapshots()
     .listen((data) => listenerUpdate(data));
     }

     void listenerUpdate(data) {
       String number = data['URL'];
      setState(() {
      _totalDocs = number;
         });
       }

[✓] Flutter (Channel unknown, 1.20.1, on Mac OS X 10.15.1 19B88, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[!] VS Code (version 1.37.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

**Comment by kevmoo** [comment]
What version of this package are you using?
Which version of the firebase JS libraries are you using?
What is the event data?
