### ISSUE TITLE
FirebaseError: Function Query.startAfter() called with invalid data. Unsupported field value: a custom object

### ISSUE THREAD

**Issue by nguyenthihuong0501** [FirebaseExtended/firebase-dart#337]
I use paging to looad the data so in the form of scrolling data
Here is the code

 public async readWithPagination(t: { new(): T },lastData: any | null, orderBy: string = 'sort',directionStr: 'desc' | 'asc'='desc') {
        let result: any | null = null
        let startAfter = lastData
        if ( startAfter == null) {
            let first = this.firestoreApp.collection(this.dataPath).orderBy(orderBy,directionStr).limit(1);
            let snapshot = await first.get();
            startAfter = snapshot.docs[snapshot.docs.length - 1];
        }
        result = await this.firestoreApp.collection(this.dataPath).orderBy(orderBy,directionStr).startAfter(startAfter).limit(1).get();
        return this.convertDocumentToModel(result, t);
    }

**Comment by kevmoo** [comment]
The code here looks like Javascript. Is this a bug w/ the Dart package or the JS code?
