### ISSUE TITLE
[firebase_auth] sendSignInLinkToEmail takes 4 minutes to arrive in inbox.

### ISSUE THREAD

**Issue by MATTYGILO** [FirebaseExtended/firebase-dart#341]
When sending a sendSignInLinkToEmail to a user it takes 4 minutes to arrive in their inbox for the first time.
When it finally arrives the date of arrival states 4 minutes prior to actual arrival. 
When I go to send the same user another email it takes only takes a few seconds. 
Why is it that this takes ages for first time sending to a user.
I have tried on both gmail and proton mail it is the same issue.

If you know a fix or want more information please ask me.

**Comment by kevmoo** [comment]
You'll likely need to inquire w/ the firebase core folks. This package just wraps the existing JS APIs – and I'm pretty sure it doesn't take 4 minutes to call the JS
