### ISSUE TITLE
Update the package for the new cloud_firestore query possibilities

### ISSUE THREAD

**Issue by LorenzoBiondani** [FirebaseExtended/firebase-dart#342]
Last week 'not equal', 'in' and 'not in' queries have been added ( https://firebase.googleblog.com/2020/09/cloud-firestore-not-equal-queries.html ).
An update to the package is needed, I don't have much time to help but if you need something let me know.

**Comment by Ehesp** [comment]
This should already be working assuming your underling Firebase version supports it. This API just takes a string value and passes it on.

**Comment by LorenzoBiondani** [comment]
Ok sorry, I can confirm it works, we need to update the docs.
https://github.com/FirebaseExtended/firebase-dart/blob/ec106a9e65656c8c8c88d12fad6d88e3ba7f7c8b/lib/src/interop/firestore_interop.dart#L230-L231
https://github.com/FirebaseExtended/firebase-dart/blob/279fae8d6d004c3d1d636a2d2b2514dc01b024b8/lib/src/firestore.dart#L536-L538

**Comment by Ehesp** [comment]
Yeah they're just there to represent tuples which don't exist in Dart. I agree though should be updated.

**Comment by kevmoo** [comment]
Fixed by 32539e94cdba5a56c878a06190b542d32169d148
