### ISSUE TITLE
Firebase syncing issue when persistance is involved

### ISSUE THREAD

**Issue by eimantas1998** [FirebaseExtended/firebase-dart#359]
Hello, the issue is that sometimes firebase does not return some of the documents that satisfy the query. The issue happens when internet connection goes out for a bit then comes back up, then some of new documents get synced and some of them just don't.

The query I am using:

```
  Stream<List<Book>> streamBooks(List<String> bookIds) =>
      _firestore
          .collectionGroup('books')
          .where(BOOK_ID, whereIn: bookIds)
          .snapshots()
          .map((snap) => snap.docs
              .map((doc) => Book.fromJson(_addDocId(doc)))
              .toList());
```

**Comment by kevmoo** [comment]
We can only help with issues specific to this package. You may want to find a Firebase-focused discussion to ask about this.
