### ISSUE TITLE
Database onValue does not call onError callback

### ISSUE THREAD

**Issue by VickyBOSS** [FirebaseExtended/firebase-dart#365]
Database onValue does not call onError callback

`fb
                .database()
                .ref("uwallets/nNcVBqsWfaY66ixRQxbwa5sXXHE3")
                .onChildChanged
                .listen((event) {
              logger.d("EVENT");
            }, onError: (err) {
// NEVERRRRRRRR prints
              logger.e("ERROR");
            });`

**Comment by kevmoo** [comment]
Looking at https://firebase.google.com/docs/reference/js/firebase.database.Query#on there is no option to provide an event handler here.

What type of error are you missing?
Can you give an example of how to trigger an error so I could create a test?
