### ISSUE TITLE
Uncaught Error: Expected a value of type 'FutureOr<UserCredentialJsImpl>', but got one of type 'MemoryInfo'

### ISSUE THREAD

**Issue by ianvillamia** [FirebaseExtended/firebase-dart#367]
Problem with Firebase Auth while using angular Dart

Dependencies:
Dart VM version: 2.7.1
firebase: 5.0.4

error
Uncaught Error: Expected a value of type 'FutureOr<UserCredentialJsImpl>', but got one of type 'MemoryInfo'

![image](https://user-images.githubusercontent.com/25190455/102009476-99c01300-3d72-11eb-94ba-52ebb7536b4d.png)

Code
```
import 'package:firebase/firebase.dart' as firebase;
 try {
       await firebase
        .auth()
        .signInWithEmailAndPassword('email', 'password')
        .then((value) => print('success'));
    } catch (e) {
      print(e);
    }

```

**Comment by kevmoo** [comment]
We do this here and have had no such issues

https://github.com/FirebaseExtended/firebase-dart/blob/32539e94cdba5a56c878a06190b542d32169d148/firebase/example/auth/index.dart#L105-L109

Please reopen with more reproduction details if you still have this problem
