### ISSUE TITLE
Add optional 'reviver' callback in 'DataSnapshot.val({reviver(var key, var value)})'

### ISSUE THREAD

**Issue by kostaa** [FirebaseExtended/firebase-dart#91]
The underlying implementation uses JSON.decode() method which takes an optional reviver function. 
Adding this callback to the DataSnapshot API would simplify processing of more complex JSON objects 
which currently require additional post-processing.

**Comment by kevmoo** [comment]
We're trying to keep this API as close to the JS API as possible – to minimize maintenance.
