### ISSUE TITLE
firebase.js doesn't work with Chrome's Content Security Policy

### ISSUE THREAD

**Issue by tonyclickspace** [FirebaseExtended/firebase-dart#94]
[Content Security Policy for Chrome Apps](https://developer.chrome.com/apps/contentSecurityPolicy)

The dart code can be compiled to obey CSP, but the javascript served at https://www.gstatic.com/firebasejs/3.6.4/firebase.js still uses string-to-JavaScript methods like eval() and new Function(), so can't be used in some Chrome Apps.

**Comment by kevmoo** [comment]
I believe this resolved.
